routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;



if(config('crud.mode') == 'mpa'){
    Route::get('/home','HomeController@index')->name('home');

    Route::get('/myprofile',  'Admin\ProfileController@showProfilePage')->name('profile');
    Route::put('/myprofile', 'Admin\ProfileController@updateProfile');
    Route::get('/password',  'Admin\ProfileController@showPasswordPage')->name('password');
    Route::put('/password',  'Admin\ProfileController@changePassword');


    Route::post('usermanagement/bulkdelete', 'Admin\UserManagementController@bulkDelete')->name('usermanagement.bulkdelete');
    Route::post('usermanagement/api', 'Admin\UserManagementController@api')->name('usermanagement.api');
    Route::resource('usermanagement', 'Admin\UserManagementController');

    Route::middleware(['auth'])->group(function(){


        Route::post('youtube/bulkdelete', 'YoutubeController@bulkDelete')->name('youtube.bulkdelete');
        Route::post('youtube/api','YoutubeController@api')->name('youtube.api');
        Route::resource('youtube', 'YoutubeController');

        //generated routes controller middleware
        Route::post('slider/bulkdelete', 'SliderController@bulkDelete')->name('slider.bulkdelete');
//    Route::post('slider/api', 'SliderController@api')->name('slider.api');
        Route::resource('slider', 'SliderController');

        Route::post('regulasi/bulkdelete', 'RegulasiController@bulkDelete')->name('regulasi.bulkdelete');
//Route::post('regulasi/api', 'RegulasiController@api')->name('regulasi.api');
        Route::resource('regulasi', 'RegulasiController');

        Route::post('kategori/bulkdelete', 'KategoriController@bulkDelete')->name('kategori.bulkdelete');
//Route::post('kategori/api', 'KategoriController@api')->name('kategori.api');
        Route::resource('kategori', 'KategoriController');

        Route::post('saran/bulkdelete', 'SaranController@bulkDelete')->name('saran.bulkdelete');
        Route::resource('saran', 'SaranController');

        Route::post('katalog/bulkdelete', 'KatalogController@bulkDelete')->name('katalog.bulkdelete');
        Route::resource('katalog', 'KatalogController');

        Route::post('halaman/bulkdelete', 'HalamanController@bulkDelete')->name('halaman.bulkdelete');
        Route::post('halaman/api', 'HalamanController@api')->name('halaman.api');
        Route::resource('halaman', 'HalamanController');

        Route::post('gallery/bulkdelete', 'GalleryController@bulkDelete')->name('gallery.bulkdelete');
        Route::resource('gallery', 'GalleryController');

        Route::post('berita/bulkdelete', 'BeritaController@bulkDelete')->name('berita.bulkdelete');
        Route::resource('berita', 'BeritaController');

        Route::post('kategoriberita/bulkdelete', 'KategoriBeritaController@bulkDelete')->name('kategoriberita.bulkdelete');
        Route::resource('kategoriberita', 'KategoriBeritaController');

        Route::post('linkterkait/bulkdelete', 'LinkTerkaitController@bulkDelete')->name('linkterkait.bulkdelete');
        Route::resource('linkterkait', 'LinkTerkaitController');

        Route::post('menu/api', 'MenuController@api')->name('menu.api');
        Route::post('menu/save', 'MenuController@save')->name('menu.save');
        Route::resource('menu', 'MenuController')->only(['destroy', 'index']);

        Route::post('pengumuman/api', 'PengumumanController@api')->name('pengumuman.api');
        Route::post('pengumuman/bulkdelete', 'PengumumanController@bulkDelete')->name('pengumuman.bulkdelete');
        Route::resource('pengumuman', 'PengumumanController');

        Route::post('propem/bulkdelete', 'PropemController@bulkDelete')->name('propem.bulkdelete');
        Route::post('propem/api', 'PropemController@api')->name('propem.api');
        Route::resource('propem', 'PropemController');

        Route::post('propempengusul/bulkdelete', 'PropemPengusulController@bulkDelete')->name('propempengusul.bulkdelete');
        Route::post('propempengusul/api', 'PropemPengusulController@api')->name('propempengusul.api');
        Route::resource('propempengusul', 'PropemPengusulController');

        Route::post('setting/bulkdelete', 'SettingController@bulkDelete')->name('setting.bulkdelete');
        Route::post('setting/api', 'SettingController@api')->name('setting.api');
        Route::resource('setting', 'SettingController');

        Route::post('settinggroup/bulkdelete', 'SettingGroupController@bulkDelete')->name('settinggroup.bulkdelete');
        Route::post('settinggroup/api', 'SettingGroupController@api')->name('settinggroup.api');
        Route::resource('settinggroup', 'SettingGroupController');

        Route::post('kontak/bulkdelete', 'KontakController@bulkDelete')->name('kontak.bulkdelete');
        Route::post('kontak/api', 'KontakController@api')->name('kontak.api');
        Route::resource('kontak', 'KontakController');

        Route::group(['prefix' => 'filemanager', 'middleware' => ['web', 'auth']], function () {
            Lfm::routes();
        });

        Route::get('/css-editor', 'CssEditorController@show')->name('css.show');
        Route::post('/css-editor', 'CssEditorController@save');

        Route::get('instagram', function (){
            $profile = \Dymantic\InstagramFeed\Profile::where('username', config('instagram-feed.username'))->first();

            return view('instagram.auth', ['instagram_auth_url' => $profile->getInstagramAuthUrl()]);
        });
    });

}else{
    Route::get('/', 'Admin\AdminController');
}

if(config('crud.use_login') == true){
    Route::get('/login', 'Admin\AuthController@showLoginForm')->name('login');
    Route::post('/login', 'Admin\AuthController@login');
    Route::post('/logout', 'Admin\AuthController@logout')->name('logout');
}

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('visitor')->group(function(){
    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('halaman/{slug}', 'WebController@viewHalaman')->name('view.halaman');


    Route::get('berita', 'WebController@berita')->name('berita');
    Route::get('view/berita/{slug}', 'WebController@viewBerita')->name('view.berita');

    Route::get('view/pengumuman/{slug}', 'WebController@pengumuman')->name('pengumuman');

    Route::get('voting', 'VotingController@index')->name('voting');
    Route::post('voting', 'VotingController@update');

    Route::get('instagram-auth-success', function (){
        abort('200', 'Auth Instagram Success');
    });

    Route::get('instagram-auth-failure', function (){
        abort('500', 'Auth Instagram Failure');
    });
});

app/Http/Controllers/BeritaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Berita;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Intervention\Image\Facades\Image;
use Yajra\DataTables\DataTables;

class BeritaController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth', 'role:admin|super-admin'])->except('api');
    }

    /**
     * @param Request $request
     * @return string
     */
    public function api(Request $request)
    {
        /* //JIKA ADA DATA YANG DIKIRIMKAN
         if ($request->hasFile('upload')) {
             $file = $request->file('upload'); //SIMPAN SEMENTARA FILENYA KE VARIABLE
             $filename = Str::random() . "." . $file->getClientOriginalExtension();
             Storage::putFileAs('/uploads/media', $file, $filename);

             //KEMUDIAN KITA BUAT RESPONSE KE CKEDITOR
             $ckeditor = $request->input('CKEditorFuncNum');
             $url = asset('uploads/media/' . $filename);
             $msg = 'Image uploaded successfully';
             //DENGNA MENGIRIMKAN INFORMASI URL FILE DAN MESSAGE
             $response = "<script>window.parent.CKEDITOR.tools.callFunction($ckeditor, '$url', '$msg')</script>";

             //SET HEADERNYA
             @header('Content-type: text/html; charset=utf-8');
             return $response;
         }*/
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     * hapus semua
     */
    public function bulkDelete(Request $request)
    {
        $data = collect($request->data);
        $save = Berita::whereIn("id", $data->pluck("id")->unique())->delete();
        return $save
            ? response()->json(['status' => true, 'text' => 'success', 'message' => 'Berita berhasil dihapus'])
            : response()->json(['status' => false, 'text' => 'error', 'message' => 'Berita gagal dihapus'], 500);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function index(Request $request)
    {
        $data = Berita::with(['kategori_berita']);
        /*if ($request->has("berita_status") && $request->berita_status != null) {
            $data = $data->where("_berita.berita_status","=", $request->berita_status);
        }*/
        if ($request->ajax()) {
            return DataTables::of($data)
                ->addColumn('action', function ( $data) {
                    return view("berita.actions_berita", ['data' => $data]);
                })
                ->editColumn('gambar', function ( $data) {
                    return "<a href='" . asset('uploads/berita/' . $data->gambar) . "'>Lihat Gambar</a>";
                })
                ->addColumn('checked', function ( $data) {
                    return view("berita.checked_berita", ['data' => $data]);
                })
                ->rawColumns(['action', 'checked', 'gambar'])
                ->toJson();
        }

        return view('berita.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('berita.create', ['modal_title' => 'Tambah Data']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $rules = [
            "kategori_id" => [
                "required"
            ],
            "judul" => [
                "required",
                Rule::unique('berita', 'judul')
            ],
            "gambar" => [
                "required"
            ],
            "isi" => [
                "required"
            ],
        ];
        $this->validate($request, $rules);

        $db = new Berita;
        $save = $this->handleRequest($request, $db);

        return $save
            ? response()->json(['status' => true, 'text' => 'success', 'message' => 'Berita berhasil ditambahkan'])
            : response()->json(['status' => false, 'text' => 'error', 'message' => 'Berita gagal ditambahkan'], 500);
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Berita $berita
     * @return \Illuminate\Http\Response
     */
    public function show(Berita $berita)
    {
        return view('berita.show', ['data' => $berita]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Berita $berita
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $berita = Berita::findOrFail($id);
        return view('berita.edit', ['data' => $berita], ['modal_title' => 'Edit Data']);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Berita $berita
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, $id)
    {
        $rules = [
            "kategori_id" => [
                "required"
            ],
            "judul" => [
                "required",
                Rule::unique('berita', 'judul')
                    ->ignore($id, 'id')

            ],
            "isi" => [
                "required"
            ],
        ];
        $this->validate($request, $rules);

        $db = Berita::findOrFail($id);
        $save = $this->handleRequest($request, $db);

        return $save
            ? response()->json(['status' => true, 'text' => 'success', 'message' => 'Berita berhasil diupdate'])
            : response()->json(['status' => false, 'text' => 'error', 'message' => 'Berita gagal diupdate'], 500);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Berita $berita
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy($id)
    {
        $save =  Berita::destroy($id);

       return $save
            ? response()->json(['status' => true, 'text' => 'success', 'message' => 'Berita berhasil dihapus'])
            : response()->json(['status' => false, 'text' => 'error', 'message' => 'Berita gagal dihapus'], 500);
    }

    /**
     * @param $request
     * @param \App\Models\Berita $db
     * @return mixed
     */
    private function handleRequest(Request $request, $db)
    {
        $db->user_id = auth()->id();
        $db->kategori_id = $request->kategori_id;
        $db->judul = $request->judul;
        $db->url = date('Y-m-d') . '-' . Str::slug($request->judul);
        if ($request->hasFile('gambar')) {
            //  Proses Gambar
            if(!$db->id){
                $directory = storage_path('app/uploads/berita');
                if (!file_exists($directory)) {
                    mkdir($directory, 0777, true);
                }
            }
            $filename = resizeGambar($request->file('gambar'), 'uploads/berita/');
            $db->gambar = $filename;
        }
        $db->isi = $request->isi;

        return $db->save();
    }
}

resources/views/berita/actions_berita.blade.php
<div class="btn-group" role="group">
    <a href="{{route('berita.edit', $data->id)}}" class="btn btn-primary btn-sm">
<span class="material-icons" style="font-size: 0.9rem">
edit
</span> Edit
    </a>
    <a href="{{route('berita.destroy', $data->id)}}" class="btn btn-danger btn-destroy btn-sm">
    <span class="material-icons" style="font-size: 0.9rem">
delete
</span>
        Hapus
    </a>

    <a href="{{route('view.berita', $data->url)}}" class="btn btn-danger btn-dark btn-sm">
    <span class="material-icons" style="font-size: 0.9rem">
        web
</span>
        Lihat Berita
    </a>
</div>

resources/views/berita/checked_berita.blade.php
<div class="custom-control custom-checkbox">
    <input type="checkbox" id="{{ $data->id }}" name="checked[]" class="custom-control-input dt-selectable" value="true">
    <label class="custom-control-label" for="{{ $data->id }}"></label>
</div>

resources/views/berita/create.blade.php
@extends('vendor.admin.layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <nav aria-label="breadcrumb" class="shadow-sm breadcrumbnav">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{route('berita.index')}}">Berita</a></li>
                        <li class="breadcrumb-item active">{{$modal_title}}</li>
                    </ol>
                </nav>
            </div>
            <div class="col-md-12">
                <div class="card border-light shadow-sm">
                    <div class="card-body">
                        <div id="app">
                            @include("berita.form", [ 'action' => route('berita.store') ])
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/berita/edit.blade.php
@extends('vendor.admin.layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <nav aria-label="breadcrumb" class="shadow-sm breadcrumbnav">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{route('berita.index')}}">Berita</a></li>
                        <li class="breadcrumb-item active">{{$modal_title}}</li>
                    </ol>
                </nav>
            </div>
            <div class="col-md-12">
                <div class="card border-light shadow-sm">
                    <div class="card-body">
                        <div id="app">
                            @include("berita.form", ['data' => $data, 'method'=> 'PUT', 'action' => route('berita.update', $data->id)])
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/berita/form.blade.php
<div>
    <form action="{{$action}}" id="formModal" method="POST">
        @csrf
        @isset($method)
            @if($method == "PUT")
                @method("PUT")
            @endif
        @endisset
        <div class="content">
            <div class="class1">
                <h5 class="modal-title">{{isset($modal_title) ? $modal_title : ""}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="mt-4">
                <div class="form-group">
                    <label for="kategori_id">Kategori</label>
                    <x-select-component id="kategori_id"
                                        name="kategori_id"
                                        case="kategori_berita"
                                        text-value="kategori_id"
                                        text-label="nama"
                                        error-container="#kategori_id-errors"
                                        :selected="isset($data) ? $data->kategori_id : ''">
                    </x-select-component>
                    <div id="kategori_id-errors"></div>
                </div>
                <div class="form-group">
                    <label for="judul">Judul</label>
                    <input name="judul" type="text"
                           data-parsley-errors-container="#judul-errors"
                           value="<?php echo e(isset($data) ? $data->judul : ""); ?>"
                           class="form-control" id="judul">
                    <div id="judul-errors"></div>
                </div>
               {{-- <div class="form-group">
                    <label for="url">URL</label>
                    <input name="url" type="text"
                           data-parsley-errors-container="#url-errors"
                           value="<?php echo e(isset($data) ? $data->url : ""); ?>"
                           class="form-control" id="url">
                    <div id="url-errors"></div>
                </div>--}}
                <div class="form-group">
                    <div class="custom-file mt-4">
                        <input name="gambar" type="file"
                               class="custom-file-input" id="gambar">
                        <label class="custom-file-label" for="gambar">Gambar</label>
                    </div>
                </div>

<!--                <div class="form-group">
                    <a id="lfm" data-input="thumbnail" data-type="Files" data-preview="holder" class="btn btn-primary text-white">
                        <i class="fa fa-file-pdf-o"></i> Buka File Manager
                    </a>
                </div>-->

                <div class="form-group">
                    <label for="isi">Isi</label>
                    <textarea name="isi" data-parsley-errors-container="#isi-errors"
                              id="isi">{!! isset($data) ? $data->isi : "" !!}</textarea>
                    <div id="isi-errors"></div>
                </div>


            </div>
            <div class="class4">
                <button type="submit" class="btn btn-primary" id="save">Simpan</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
            </div>
        </div>
    </form>
</div>

@push("style")
    <link rel="stylesheet" type="text/css"
          href="{{ asset('vendor/crudgen/libs/datatables/datatables.min.css') }}"/>
    <link rel="stylesheet" type="text/css"
          href="{{ asset('vendor/crudgen/libs/select2/select2.min.css') }}"/>
@endpush


@push("script")
    <script src="{{ asset('vendor/crudgen/libs/mask/dist/jquery.mask.min.js') }}"></script>
    <script src="{{ asset('vendor/crudgen/libs/etc/moment.min.js') }}"></script>
    <script src="{{ asset('vendor/crudgen/libs/select2/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('vendor/crudgen/libs/datatables/pdfmake.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('vendor/crudgen/libs/datatables/vfs_fonts.js') }}"></script>
    <script type="text/javascript"
            src="{{ asset("vendor/crudgen/libs/datatables/datatables.min.js") }}"></script>
    <script src="{{ asset('vendor/crudgen/libs/etc/loadingoverlay.js') }}"></script>
    <script src="{{ asset('vendor/crudgen/libs/etc/jqueryform.js') }}"></script>

    <script src="{{asset('vendor/crudgen/libs/ckeditor/ckeditor.js')}}"></script>
    <script type="text/javascript" src="{{asset('vendor/crudgen/libs/ckeditor/adapters/jquery.js')}}"></script>
    <script src="{{asset('vendor/laravel-filemanager/js/stand-alone-button.js')}}"></script>
    <script src="{{asset('vendor/crudgen/libs/etc/init.js')}}"></script>
    <script>
        $(document).ready(function () {
            $('#lfm').filemanager('Files', {prefix: "{{url('filemanager')}}"});

            $('#isi').ckeditor(function () { /* callback code */
            }, {
                language: 'id',
                height: '800px',
                filebrowserBrowseUrl: '{{url('filemanager')}}',
                iframebrowserBrowseUrl: '{{url('filemanager')}}',
            });

            /*CKEDITOR.editorConfig = function( config ) {
                config.extraPlugins = 'mediabrowser';
            };*/


            $("#formModal").on("submit", function (e) {
                e.preventDefault();
                e.stopImmediatePropagation();
                var serializedArray = $(this).serializeArray();
                $.each(serializedArray, function (index, value) {
                    let el = $(`#${value.name}-errors`);
                    el.html("");
                });
                $(this).ajaxSubmit({
                    success: function (response) {
                        alertify.success(response.message);
                        dt.ajax.reload(null, false);
                    },
                    error: function (error) {
                        alertify.error(error.responseJSON.message);
                        var errorBags = error.responseJSON.errors;
                        console.log(errorBags);
                        $.each(errorBags, function (index, value) {
                            let el = $(`#${index}-errors`);
                            el.html(`<small class='text-danger'>${value.join()}</small>`);
                        });
                    }
                });
                return false;
            });
        })
        ;
    </script>
@endpush