routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;



if(config('crud.mode') == 'mpa'){
    Route::get('/home','HomeController@index')->name('home');

    Route::get('/myprofile',  'Admin\ProfileController@showProfilePage')->name('profile');
    Route::put('/myprofile', 'Admin\ProfileController@updateProfile');
    Route::get('/password',  'Admin\ProfileController@showPasswordPage')->name('password');
    Route::put('/password',  'Admin\ProfileController@changePassword');


    Route::post('usermanagement/bulkdelete', 'Admin\UserManagementController@bulkDelete')->name('usermanagement.bulkdelete');
    Route::post('usermanagement/api', 'Admin\UserManagementController@api')->name('usermanagement.api');
    Route::resource('usermanagement', 'Admin\UserManagementController');

    Route::middleware(['auth'])->group(function(){


        Route::post('youtube/bulkdelete', 'YoutubeController@bulkDelete')->name('youtube.bulkdelete');
        Route::post('youtube/api','YoutubeController@api')->name('youtube.api');
        Route::resource('youtube', 'YoutubeController');

        //generated routes controller middleware
        Route::post('slider/bulkdelete', 'SliderController@bulkDelete')->name('slider.bulkdelete');
//    Route::post('slider/api', 'SliderController@api')->name('slider.api');
        Route::resource('slider', 'SliderController');

        Route::post('regulasi/bulkdelete', 'RegulasiController@bulkDelete')->name('regulasi.bulkdelete');
//Route::post('regulasi/api', 'RegulasiController@api')->name('regulasi.api');
        Route::resource('regulasi', 'RegulasiController');

        Route::post('kategori/bulkdelete', 'KategoriController@bulkDelete')->name('kategori.bulkdelete');
//Route::post('kategori/api', 'KategoriController@api')->name('kategori.api');
        Route::resource('kategori', 'KategoriController');

        Route::post('saran/bulkdelete', 'SaranController@bulkDelete')->name('saran.bulkdelete');
        Route::resource('saran', 'SaranController');

        Route::post('katalog/bulkdelete', 'KatalogController@bulkDelete')->name('katalog.bulkdelete');
        Route::resource('katalog', 'KatalogController');

        Route::post('halaman/bulkdelete', 'HalamanController@bulkDelete')->name('halaman.bulkdelete');
        Route::post('halaman/api', 'HalamanController@api')->name('halaman.api');
        Route::resource('halaman', 'HalamanController');

        Route::post('gallery/bulkdelete', 'GalleryController@bulkDelete')->name('gallery.bulkdelete');
        Route::resource('gallery', 'GalleryController');

        Route::post('berita/bulkdelete', 'BeritaController@bulkDelete')->name('berita.bulkdelete');
        Route::resource('berita', 'BeritaController');

        Route::post('kategoriberita/bulkdelete', 'KategoriBeritaController@bulkDelete')->name('kategoriberita.bulkdelete');
        Route::resource('kategoriberita', 'KategoriBeritaController');

        Route::post('linkterkait/bulkdelete', 'LinkTerkaitController@bulkDelete')->name('linkterkait.bulkdelete');
        Route::resource('linkterkait', 'LinkTerkaitController');

        Route::post('menu/api', 'MenuController@api')->name('menu.api');
        Route::post('menu/save', 'MenuController@save')->name('menu.save');
        Route::resource('menu', 'MenuController')->only(['destroy', 'index']);

        Route::post('pengumuman/api', 'PengumumanController@api')->name('pengumuman.api');
        Route::post('pengumuman/bulkdelete', 'PengumumanController@bulkDelete')->name('pengumuman.bulkdelete');
        Route::resource('pengumuman', 'PengumumanController');

        Route::post('propem/bulkdelete', 'PropemController@bulkDelete')->name('propem.bulkdelete');
        Route::post('propem/api', 'PropemController@api')->name('propem.api');
        Route::resource('propem', 'PropemController');

        Route::post('propempengusul/bulkdelete', 'PropemPengusulController@bulkDelete')->name('propempengusul.bulkdelete');
        Route::post('propempengusul/api', 'PropemPengusulController@api')->name('propempengusul.api');
        Route::resource('propempengusul', 'PropemPengusulController');

        Route::post('setting/bulkdelete', 'SettingController@bulkDelete')->name('setting.bulkdelete');
        Route::post('setting/api', 'SettingController@api')->name('setting.api');
        Route::resource('setting', 'SettingController');

        Route::post('settinggroup/bulkdelete', 'SettingGroupController@bulkDelete')->name('settinggroup.bulkdelete');
        Route::post('settinggroup/api', 'SettingGroupController@api')->name('settinggroup.api');
        Route::resource('settinggroup', 'SettingGroupController');

        Route::post('kontak/bulkdelete', 'KontakController@bulkDelete')->name('kontak.bulkdelete');
        Route::post('kontak/api', 'KontakController@api')->name('kontak.api');
        Route::resource('kontak', 'KontakController');

        Route::group(['prefix' => 'filemanager', 'middleware' => ['web', 'auth']], function () {
            Lfm::routes();
        });

        Route::get('/css-editor', 'CssEditorController@show')->name('css.show');
        Route::post('/css-editor', 'CssEditorController@save');

        Route::get('instagram', function (){
            $profile = \Dymantic\InstagramFeed\Profile::where('username', config('instagram-feed.username'))->first();

            return view('instagram.auth', ['instagram_auth_url' => $profile->getInstagramAuthUrl()]);
        });
    });

}else{
    Route::get('/', 'Admin\AdminController');
}

if(config('crud.use_login') == true){
    Route::get('/login', 'Admin\AuthController@showLoginForm')->name('login');
    Route::post('/login', 'Admin\AuthController@login');
    Route::post('/logout', 'Admin\AuthController@logout')->name('logout');
}

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('visitor')->group(function(){
    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('halaman/{slug}', 'WebController@viewHalaman')->name('view.halaman');


    Route::get('berita', 'WebController@berita')->name('berita');
    Route::get('view/berita/{slug}', 'WebController@viewBerita')->name('view.berita');

    Route::get('view/pengumuman/{slug}', 'WebController@pengumuman')->name('pengumuman');

    Route::get('voting', 'VotingController@index')->name('voting');
    Route::post('voting', 'VotingController@update');

    Route::get('instagram-auth-success', function (){
        abort('200', 'Auth Instagram Success');
    });

    Route::get('instagram-auth-failure', function (){
        abort('500', 'Auth Instagram Failure');
    });
});

app/Models/Saran.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * App\Models\Saran
 *
 * @property int $saran_id
 * @property string|null $saran_content
 * @property \Illuminate\Support\Carbon|null $deleted_at
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|Saran newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Saran newQuery()
 * @method static \Illuminate\Database\Query\Builder|Saran onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|Saran query()
 * @method static \Illuminate\Database\Eloquent\Builder|Saran whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Saran whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Saran whereSaranContent($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Saran whereSaranId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Saran whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|Saran withTrashed()
 * @method static \Illuminate\Database\Query\Builder|Saran withoutTrashed()
 * @mixin \Eloquent
 */
/**
 * App\Models\Saran
 *
 * @property int $saran_id
 * @property string|null $saran_content
 * @property \Illuminate\Support\Carbon|null $deleted_at
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|Saran newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Saran newQuery()
 * @method static \Illuminate\Database\Query\Builder|Saran onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|Saran query()
 * @method static \Illuminate\Database\Eloquent\Builder|Saran whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Saran whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Saran whereSaranContent($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Saran whereSaranId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Saran whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|Saran withTrashed()
 * @method static \Illuminate\Database\Query\Builder|Saran withoutTrashed()
 * @mixin \Eloquent
 */
class Saran extends Model
{
    protected $table = "saran";

    protected $primaryKey = "saran_id";

//    use SoftDeletes;
}

app/Http/Controllers/SaranController.php
<?php

namespace App\Http\Controllers;

use App\Models\Saran;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Yajra\DataTables\DataTables;

class SaranController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth','role:admin|super-admin'])->except('api');
    }

    public function api(Request $request)
    {

    }

    /**
        * @param Request $request
        * @return \Illuminate\Http\JsonResponse
        * hapus semua
        */
       public function bulkDelete(Request $request)
       {
           $data = collect($request->data);
           $save = Saran::whereIn("saran_id", $data->pluck("id")->unique())->delete();
           return $save
               ? response()->json(['status' => true, 'text' => 'success', 'message' => 'Saran berhasil dihapus'])
               : response()->json(['status' => false, 'text' => 'error', 'message' => 'Saran gagal dihapus'], 500);
       }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function index(Request $request)
    {
        $data = Saran::query();
        /*if ($request->has("saran_status") && $request->saran_status != null) {
            $data = $data->where("_saran.saran_status","=", $request->saran_status);
        }*/
        if ($request->ajax()) {
            return DataTables::of($data)
                ->addColumn('action', function (Saran $data) {
                    return view("saran.actions_saran", ['data' => $data]);
                })
                ->addColumn('checked', function (Saran $data) {
                    return view("saran.checked_saran", ['data' => $data]);
                })
                ->rawColumns(['action','checked'])
                ->toJson();
        }

        return view('saran.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('saran.create',['modal_title'=>'Tambah Data']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $rules = [
    "saran_content" => [
    "required"
    ],
];
$this->validate($request, $rules);

        $db = new Saran;
        $save = $this->handleRequest($request, $db);

        return $save
            ? response()->json(['status' => true, 'text' => 'success', 'message' => 'Saran berhasil ditambahkan'])
            : response()->json(['status' => false, 'text' => 'error', 'message' => 'Saran gagal ditambahkan'], 500);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Saran $saran
     * @return \Illuminate\Http\Response
     */
    public function show(Saran $saran)
    {
        return view('saran.show', ['data' => $saran]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Saran $saran
     * @return \Illuminate\Http\Response
     */
    public function edit(Saran $saran)
    {
        return view('saran.edit', ['data' => $saran], ['modal_title'=>'Edit Data']);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Saran $saran
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, Saran $saran)
    {

       $rules = [
    "saran_content" => [
    "required"
    ],
];
$this->validate($request, $rules);

        $db = $saran;
        $save = $this->handleRequest($request, $db);

        return $save
            ? response()->json(['status' => true, 'text' => 'success', 'message' => 'Saran berhasil diupdate'])
            : response()->json(['status' => false, 'text' => 'error', 'message' => 'Saran gagal diupdate'], 500);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Saran $saran
     * @return \Illuminate\Http\Response
     */
    public function destroy(Saran $saran)
    {
        $save = $saran->delete();

        return $save
            ? response()->json(['status' => true, 'text' => 'success', 'message' => 'Saran berhasil dihapus'])
            : response()->json(['status' => false, 'text' => 'error', 'message' => 'Saran gagal dihapus'], 500);
    }

    /**
     * @param $request
     * @param \App\Models\Saran $db
     * @return mixed
     */
    private function handleRequest(Request $request, $db)
    {
        $db->saran_content = $request->saran_content;

        return $db->save();
    }
}

resources/views/saran/actions_saran.blade.php
<div class="btn-group" role="group">
    <a href="{{route('saran.edit', $data->saran_id)}}" class="btn btn-primary btn-edit btn-sm">
<span class="material-icons" style="font-size: 0.9rem">
edit
</span> Edit
    </a>
    <a href="{{route('saran.destroy', $data->saran_id)}}" class="btn btn-danger btn-destroy btn-sm">
    <span class="material-icons" style="font-size: 0.9rem">
delete
</span>
        Hapus
    </a>
</div>

resources/views/saran/checked_saran.blade.php
<div class="custom-control custom-checkbox">
    <input type="checkbox" id="{{ $data->saran_id }}" name="checked[]" class="custom-control-input dt-selectable" value="true">
    <label class="custom-control-label" for="{{ $data->saran_id }}"></label>
</div>

resources/views/saran/create.blade.php
@include("saran.form", [ 'action' => route('saran.store') ])

resources/views/saran/edit.blade.php
@include("saran.form", ['data' => $data, 'method'=> 'PUT', 'action' => route('saran.update', $data->saran_id)])

resources/views/saran/form.blade.php
<div class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-xl" role="document">
        <form action="{{$action}}" id="formModal" method="POST" >
            @csrf
            @isset($method)
            @if($method == "PUT")
            @method("PUT")
            @endif
            @endisset
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{isset($modal_title) ? $modal_title : ""}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
            <label for="saran_content">Isi</label>
            <input name="saran_content" type="text"
                   data-parsley-errors-container="#saran_content-errors"
                   value="<?php echo e(isset($data) ? $data->saran_content : ""); ?>"
                   class="form-control" id="saran_content">
            <div id="saran_content-errors"></div>
        </div>

                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script src="{{asset('vendor/crudgen/libs/etc/init.js')}}"></script>
<script>
    $("#formModal").on("submit", function (e) {
        e.preventDefault();
        e.stopImmediatePropagation();
        var serializedArray = $(this).serializeArray();
        $.each(serializedArray, function (index, value) {
            let el = $(`#${value.name}-errors`);
            el.html("");
        });
        $(this).ajaxSubmit({
            success: function (response) {
                alertify.success(response.message);
                dt.ajax.reload(null, false);
            },
            error: function (error) {
                alertify.error(error.responseJSON.message);
                var errorBags = error.responseJSON.errors;
                console.log(errorBags);
                $.each(errorBags, function (index, value) {
                    let el = $(`#${index}-errors`);
                    el.html(`<small class='text-danger'>${value.join()}</small>`);
                });
            }
        });
        return false;
    });
</script>

resources/views/saran/index.blade.php
@extends('vendor.admin.layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <nav aria-label="breadcrumb" class="shadow-sm breadcrumbnav">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active">Saran</li>
                    </ol>
                </nav>
            </div>
            <div class="col-md-12">
                <div class="card border-light shadow-sm">
                    <div class="card-body">
                        <div class="d-md-flex" id="app">
                            <h4 class="card-title mb-3">Saran</h4>
                            <div class="ml-auto">
                                <a href="{{route('saran.create')}}" class="btn btn-primary btn-create mb-1">
                                    <span class="fa fa-plus"></span>
                                    Tambah
                                </a>
                                <button class="btn btn-dark btn-refresh mb-1">
                                    <span class="fa fa-recycle"></span>
                                    Refresh Datatable
                                </button>
                                <button class="btn btn-danger btn-bulk-delete mb-1" @click="bulkDelete"
                                        v-if="data.length > 0">
                                    <span class="fa fa-trash"></span>
                                    Hapus Data Terpilih
                                </button>
                            </div>
                        </div>
                        {{-- <div class="mt-3">
                                                    <x-select-component id="saran_status_filter"
                                                                        name="saran_status"
                                                                        case="status">
                                                    </x-select-component>
                                                </div>--}}
                        <div class="mt-3">
                           <div class="table-responsive">
                            <table id="datatables" class="table dt-responsive nowrap"></table>
                           </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="modalAjaxContainer"></div>
@endsection

@push("style")
    <link rel="stylesheet" type="text/css"
          href="{{ asset('vendor/crudgen/libs/datatables/datatables.min.css') }}"/>
    <link rel="stylesheet" type="text/css"
          href="{{ asset('vendor/crudgen/libs/select2/select2.min.css') }}"/>
@endpush


@push("script")
        <script src="{{ asset('vendor/crudgen/libs/mask/dist/jquery.mask.min.js') }}"></script>
               <script src="{{ asset('vendor/crudgen/libs/etc/moment.min.js') }}"></script>
               <script src="{{ asset('vendor/crudgen/libs/select2/select2.min.js') }}"></script>
               <script type="text/javascript" src="{{ asset('vendor/crudgen/libs/datatables/pdfmake.min.js') }}"></script>
               <script type="text/javascript" src="{{ asset('vendor/crudgen/libs/datatables/vfs_fonts.js') }}"></script>
               <script type="text/javascript"
                       src="{{ asset("vendor/crudgen/libs/datatables/datatables.min.js") }}"></script>
               <script src="{{ asset('vendor/crudgen/libs/etc/loadingoverlay.js') }}"></script>
               <script src="{{ asset('vendor/crudgen/libs/etc/jqueryform.js') }}"></script>
    <script>
        $.LoadingOverlaySetup({
            background: "rgba(0, 0, 0, 0.5)",
            image: "{{asset('/images/800.svg')}}",
            imageColor: "#f0ffad"
        });
        var app = new Vue({
            el: "#app",
            data: {
                data: []
            },
            methods: {
                bulkDelete() {
                    var $vm = this;
                    alertify.confirm('Confirm Message', function () {
                        $.ajax({
                            method: "POST",
                            data: {
                                "_token": "{{ csrf_token() }}",
                                data: $vm.data
                            },
                            url: "{{route('saran.bulkdelete')}}",
                            success: function (response) {
                                alertify.success(response.message);
                                // user paging is not reset on reload
                                dt.ajax.reload(null, false);
                                $vm.data = [];
                            }
                        });
                    });
                }
            }
        });
        var configDt = {
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.21/i18n/Indonesian.json"
            },
            "dom": 'lBfrtip',
            "buttons": [
                {
                    extend: 'excelHtml5',
                    message: "Report Saran",
                    exportOptions: {
                        columns: [1, 2]
                    }
                },
                {
                    extend: 'print',
                    message: "<h4>Report Saran</h4>",
                    exportOptions: {
                        columns: [1, 2]
                    },
                    customize: function (win) {

                        var last = null;
                        var current = null;
                        var bod = [];

                        var css = '@page { size: landscape; }',
                            head = win.document.head || win.document.getElementsByTagName('head')[0],
                            style = win.document.createElement('style');

                        style.type = 'text/css';
                        style.media = 'print';

                        if (style.styleSheet) {
                            style.styleSheet.cssText = css;
                        }
                        else {
                            style.appendChild(win.document.createTextNode(css));
                        }
                        head.appendChild(style);
                    }
                },
                'colvis',
            ],
            "ajax": {
                "url": '{{url()->current()}}',
                "data": {
                    "saran_status": null
                }
            },
            "processing": true,
            "serverSide": true,
            "responsive": true,
            "order": [
                [1, "asc"]
            ],
            "columns": [
{
"data": "checked",
"name": "checked",
"orderable": false,
"searchable": false,
"title": "#",
"class": "w-10",
},
    {
    "data": "saran_content",
    "name": "saran_content",
    "orderable": true,
    "searchable": true,
    "title": "Isi",
    "class": "auto text-capitalize"
    },
{
"data": "action",
"orderable": false,
"searchable": false,
"title": "Action",
"class": "text-center w-25"
}
]

        };

        window.dt;

        $(document).ready(function () {
            dt = $('#datatables').DataTable(configDt).on("click", ".btn-edit", function (e) {
                e.preventDefault();
                $.LoadingOverlay("show")
                $.ajax({
                    method: "GET",
                    url: $(this).attr("href"),
                    success: function (response) {
                        $.LoadingOverlay("hide")
                        $("#modalAjaxContainer").html(response);
                        $("#modalAjaxContainer").find(".modal").modal("show");
                    }
                })
            }).on("click", ".btn-destroy", function (e) {
                var vm = $(this);
                e.preventDefault();
                alertify.confirm('Apakah Anda Yakin','Hapus Data Sekarang?', function () {
                    $.ajax({
                        method: "DELETE",
                        data: {
                            "_token": "{{ csrf_token() }}"
                        },
                        url: vm.attr("href"),
                        success: function (response) {
                            alertify.success(response.message);
                             dt.ajax.reload(null, false);
                        }
                    });
                },  function(){
                                       alertify.error('Cancel')
                                   });
            }).on("change", ".dt-selectable", function (e) {
                if ($(this).is(':checked')) {
                    $(this).attr('value', 'true');
                } else {
                    $(this).attr('value', 'false');
                }
                var val = $(this).val()
                var id = $(this).attr('id');
                let obj = {
                    id: id,
                    val: val
                }
                if (obj.val == "true") {
                    app.data.push(obj);
                } else {
                    var i = app.data.indexOf(obj);
                    app.data.splice(i, 1);
                }
            });
        });

        $("#saran_status_filter").on("change", function (e) {
            configDt.ajax.data.saran_status = $(this).val();
            dt.destroy();
            dt = $('#datatables').DataTable(configDt)
        });
        $(".btn-refresh").on("click", function () {
            dt.ajax.reload(null, false);
        });
        $(".btn-create").on("click", function (e) {
            e.preventDefault();
            $.LoadingOverlay("show");
            var vm = $(this);
            $.ajax({
                method: "GET",
                url: vm.attr("href"),
                success: function (response) {
                    $.LoadingOverlay("hide")
                    $("#modalAjaxContainer").html(response);
                    $("#modalAjaxContainer").find(".modal").modal("show");
                }
            })
        });
    </script>
@endpush